#!/usr/bin/env bash
#-----------------------------------------------------------------------------
# Regenerate the eicke key store — all key material the build signs with.
#
# The build container mounts the host key dir at /yocto/keys (see dock.sh) and
# the recipes read their keys from there (EICKE_KEYS_DIR). This script (re)creates:
#
#   swupdate-priv.pem / swupdate-public.pem
#       RSA-4096 keypair for the SWUpdate .swu signature (RSA-PSS). The PUBLIC
#       key is also shipped inside the image, so it is copied into the layer at
#       recipes-support/swupdate-public-key/files/swupdate-public.pem — the two
#       MUST match or on-device .swu verification fails. See swupdate-signing.inc.
#
#   eicke-fit.key / eicke-fit.crt
#       RSA-2048 key + self-signed cert for the signed kernel FIT on
#       qemuarm-uboot (eicke-image-prod). See conf/machine/include/eicke-verified-boot.inc.
#
#   sb-user/  (only with --secure-boot)
#       UEFI Secure Boot / TPM / IMA user key store for the x86 prod image,
#       generated by meta-secure-core's create-user-key-store.sh. Requires the
#       meta-secure-core layer to be checked out. See doc/secure-boot-setup.md.
#
# By default existing keys are KEPT (only missing ones are generated). Use
# --force to overwrite.
#
# WARNING: regenerating a key invalidates everything already signed with the old
# one. After --force you must rebuild the images AND re-provision devices:
#   - swupdate: reflash/redeploy so the device carries the new public key;
#   - eicke-fit: rebuild eicke-image-prod (the FIT is re-signed);
#   - secure boot: re-enroll the new db cert into firmware (sb-user/fw-enroll).
#-----------------------------------------------------------------------------
set -euo pipefail

PROGNAME="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAYER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"                 # meta-eicke/

# Defaults
KEYDIR="${EICKE_KEYS_DIR:-${HOME}/yocto/keys}"
FORCE=0
DO_SECUREBOOT=0
SB_PASS=""
SWUPDATE_BITS=4096
FIT_BITS=2048
CERT_DAYS=3650

usage() {
    cat <<EOF
Usage: ${PROGNAME} [options]

  --keydir DIR     Key store directory (default: \$EICKE_KEYS_DIR or ~/yocto/keys)
  --force          Overwrite existing keys (DANGEROUS — see the header warning)
  --secure-boot    Also (re)generate the UEFI Secure Boot store (sb-user/);
                   needs meta-secure-core checked out
  --sb-pass PW     Password for the Secure Boot GPG/boot keys (default: random,
                   printed at the end). Only used with --secure-boot.
  -h, --help       This help

By default only MISSING keys are created; existing keys are left untouched.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --keydir)      KEYDIR="$2"; shift 2 ;;
        --force)       FORCE=1; shift ;;
        --secure-boot) DO_SECUREBOOT=1; shift ;;
        --sb-pass)     SB_PASS="$2"; shift 2 ;;
        -h|--help)     usage; exit 0 ;;
        *) echo "ERROR: unknown option '$1'" >&2; usage >&2; exit 1 ;;
    esac
done

command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl not found" >&2; exit 1; }

mkdir -p "${KEYDIR}"
echo "Key store: ${KEYDIR}"
[ "${FORCE}" = 1 ] && echo "Mode: --force (existing keys WILL be overwritten)"

# Generate only if absent, unless --force. Returns 0 if we should (re)generate.
should_write() {
    local f="$1"
    if [ -e "${f}" ] && [ "${FORCE}" != 1 ]; then
        echo "  keep (exists): ${f##*/}"
        return 1
    fi
    return 0
}

#--- SWUpdate RSA-PSS signing keypair ----------------------------------------
gen_swupdate() {
    local priv="${KEYDIR}/swupdate-priv.pem"
    local pub="${KEYDIR}/swupdate-public.pem"
    local layer_pub="${LAYER_DIR}/recipes-support/swupdate-public-key/files/swupdate-public.pem"

    if should_write "${priv}"; then
        echo "  generate: swupdate-priv.pem (RSA-${SWUPDATE_BITS})"
        openssl genrsa -out "${priv}" "${SWUPDATE_BITS}" 2>/dev/null
        chmod 600 "${priv}"
        # public key always regenerated from the (new) private key
        openssl rsa -in "${priv}" -pubout -out "${pub}" 2>/dev/null
        chmod 644 "${pub}"
    elif [ ! -e "${pub}" ]; then
        # private kept but public missing: derive it
        echo "  derive: swupdate-public.pem (from existing private key)"
        openssl rsa -in "${priv}" -pubout -out "${pub}" 2>/dev/null
        chmod 644 "${pub}"
    fi

    # Keep the in-tree public key (shipped in the image) in sync with the store.
    if [ -f "${layer_pub}" ] && cmp -s "${pub}" "${layer_pub}"; then
        echo "  in-tree swupdate-public.pem already matches"
    else
        cp "${pub}" "${layer_pub}"
        echo "  synced in-tree public key -> ${layer_pub#${LAYER_DIR}/}"
        echo "    (commit this change so the image ships the matching key)"
    fi
}

#--- FIT kernel-image signing key + cert -------------------------------------
gen_fit() {
    local key="${KEYDIR}/eicke-fit.key"
    local crt="${KEYDIR}/eicke-fit.crt"

    if should_write "${key}"; then
        echo "  generate: eicke-fit.key (RSA-${FIT_BITS}) + eicke-fit.crt"
        openssl genrsa -F4 -out "${key}" "${FIT_BITS}" 2>/dev/null
        chmod 600 "${key}"
        openssl req -batch -new -x509 -days "${CERT_DAYS}" \
            -key "${key}" -out "${crt}" -subj "/CN=eicke-fit" 2>/dev/null
        chmod 644 "${crt}"
    elif [ ! -e "${crt}" ]; then
        echo "  generate: eicke-fit.crt (from existing key)"
        openssl req -batch -new -x509 -days "${CERT_DAYS}" \
            -key "${key}" -out "${crt}" -subj "/CN=eicke-fit" 2>/dev/null
        chmod 644 "${crt}"
    fi
}

#--- UEFI Secure Boot user key store (optional) ------------------------------
gen_secureboot() {
    local sbdir="${KEYDIR}/sb-user"
    local sbscript
    sbscript="$(find "${LAYER_DIR}/.." -path '*meta-signing-key/scripts/create-user-key-store.sh' 2>/dev/null | head -1)"

    if [ -z "${sbscript}" ]; then
        echo "  SKIP secure boot: create-user-key-store.sh not found" \
             "(meta-secure-core not checked out)"
        return 0
    fi
    if [ -d "${sbdir}" ] && [ "${FORCE}" != 1 ]; then
        echo "  keep (exists): sb-user/  (use --force to regenerate)"
        return 0
    fi
    [ -d "${sbdir}" ] && rm -rf "${sbdir}"

    if [ -z "${SB_PASS}" ]; then
        SB_PASS="$(openssl rand -base64 12)"
        echo "  secure-boot: generated password (write it down): ${SB_PASS}"
    fi
    echo "  generate: sb-user/ via create-user-key-store.sh"
    "${sbscript}" -d "${sbdir}" \
        -rp "${SB_PASS}" -bgp "${SB_PASS}" -bp "${SB_PASS}" -ip "${SB_PASS}"
    echo "    re-enroll sb-user/uefi_sb_keys into firmware (see doc/secure-boot-setup.md)"
}

gen_swupdate
gen_fit
[ "${DO_SECUREBOOT}" = 1 ] && gen_secureboot

echo
echo "Done. Key store contents:"
ls -l "${KEYDIR}" | sed 's/^/  /'
